
run:
  timeout: 5m
  skip-dirs:
    - internal/infrastructure/drivers/redis.go

linters:
  enable:
    - gofmt
    - goimports
    - revive
    - govet
    - staticcheck
    - unused
    - misspell
    - ineffassign
    - typecheck

linters-settings:
  goimports:
    local-prefixes: mymodule

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
